
name: Back up database

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 5 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, backup]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run backup and pull data
        run: |
          cd ~,
          wg-quick up wg0.conf,
          ssh root@45.33.25.204,
          docker exec -t some-postgres pg_dumpall -c -U postgres > dumps/dump_`date +%d-%m-%Y`.sql,
          exit,
          scp -r root@45.33.25.204:/root/dumps .,
          
          
