
name: Restore

on:
  workflow_dispatch:
    inputs:
      month:
        description: 'month of backup'
        required: true
      day:
        description: 'day of backup'
        required: true

jobs:

  push:

    runs-on: [self-hosted, backup]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ~
          wg-quick up wg0
          scp -r "dumps/dump_${{github.event.inputs.day}}-${{github.event.inputs.month}}-2022.sql" root@45.33.25.204:/root
          wg-quick down wg0
          
  restore:
    runs-on: [self-hosted, docker]
    needs: push
    steps:
      - uses: actions/checkout@v2
      
      - name: Restore database
        run: |
          cd ~
          cat "dumps/dump_${{github.event.inputs.day}}-${{github.event.inputs.month}}-2022.sql" | docker exec -i some-postgres psql -U postgres
          
          
          
